FROM node:13.7.0

# copy package.json and package-lock.json into /usr/app
WORKDIR /usr/app

COPY package*.json ./

RUN rm -rf node_modules && yarn install --frozen-lockfile

COPY . .

# start the test server
CMD ["yarn", "test"]

